export const userConstants = {
  USER_REGISTER_REQUEST: `USER_REGISTER_REQUEST`,
  USER_REGISTER_SUCCESS: `USER_REGISTER_SUCCESS`,
  USER_REGISTER_FAIL: `USER_REGISTER_FAIL`,
  USER_REGISTER_RESET: `USER_REGISTER_RESET`,

  USER_LOGIN_REQUEST: `USER_LOGIN_REQUEST`,
  USER_LOGIN_SUCCESS: `USER_LOGIN_SUCCESS`,
  USER_LOGIN_FAIL: `USER_LOGIN_FAIL`,
  USER_LOGOUT: `USER_LOGOUT`,

  SET_ERROR_TO_NULL: `SET_ERROR_TO_NULL`,
};

export const productConstants = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',

  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',
};

export const cartConstants = {
  CART_ADD_ITEM: `CART_ADD_ITEM`,
  CART_REMOVE_ITEM: `CART_REMOVE_ITEM`,
};
